### ISSUE TITLE
add-1-on-1-voice-calling sample can't run 

### ISSUE THREAD

**Issue by osamum** [Azure-Samples/communication-services-javascript-quickstarts#112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Open add-1-on-1-voice-calling sample project with the terminal window.
> 2. Run `npm i` on the directory of the project to install dependencies
> 3. Run the following command.
>    npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map
> An error has occured.

### Any log messages given by the failure
> Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : yes
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: add-1-on-1-voice-calling@1.0.0
> npm ERR! Found: webpack@4.46.0
> npm ERR! node_modules/webpack
> npm ERR!   dev webpack@"^4.46.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer webpack@"5.x.x" from @webpack-cli/serve@2.0.1
> npm ERR! node_modules/@webpack-cli/serve
> npm ERR!   dev @webpack-cli/serve@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! 
> npm ERR! For a full report see:
> npm ERR! C:\Users\osamum\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-eresolve-report.txt

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\user01\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-debug-0.log
> undefinedWould you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : yes
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: add-1-on-1-voice-calling@1.0.0
> npm ERR! Found: webpack@4.46.0
> npm ERR! node_modules/webpack
> npm ERR!   dev webpack@"^4.46.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer webpack@"5.x.x" from @webpack-cli/serve@2.0.1
> npm ERR! node_modules/@webpack-cli/serve
> npm ERR!   dev @webpack-cli/serve@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! 
> npm ERR! For a full report see:
> npm ERR! C:\Users\user01\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-eresolve-report.txt

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User01\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-debug-0.log
> undefined Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : yes
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: add-1-on-1-voice-calling@1.0.0
> npm ERR! Found: webpack@4.46.0
> npm ERR! node_modules/webpack
> npm ERR!   dev webpack@"^4.46.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer webpack@"5.x.x" from @webpack-cli/serve@2.0.1
> npm ERR! node_modules/@webpack-cli/serve
> npm ERR!   dev @webpack-cli/serve@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! 
> npm ERR! For a full report see:
> npm ERR! C:\Users\User01\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-eresolve-report.txt

> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\User01\AppData\Local\npm-cache\_logs\2023-03-31T06_12_02_739Z-debug-0.log
> undefined

### Expected/desired behavior
> The sample application runs fine.

### OS and Version?
> Windows 11 + Microsoft Edge

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by enricohuang** [comment]
@osamum 
The error message appears because the webpack cli tool tried to install latest webpack-cli/server and it is not compatible to the versions you have installed.

Could you delete the `node_modules` folder and rerun the step 2 `npm install`
After the step2, you should be able see `node_modules` again.
Check the folder `node_modules\.bin`, there should be webpack-dev-server files
Then run  `npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map`

**Comment by palatter** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Please feel free to reopen this issue if you have any questions.
