### ISSUE TITLE
Cannot start call on 1-on-1 video-calling

### ISSUE THREAD

**Issue by canperk** [Azure-Samples/communication-services-javascript-quickstarts#13]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run : npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map

### Any log messages given by the failure
> Unable to parse endpoint metadata

### Expected/desired behavior
> Start the call

### OS and Version?
> Windows 10

### Versions
> 1.0.0

### Mention any other details that might be useful
Hi! I am trying to call a peer over 'add-1-on-1-video-calling' sample and I just started code as it is described by running:

`npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map`

Application is built but I can not start a call after setting 'userIdToCall' variable to any string value. Is it Skype account name or is it a mail? Whatever I tried, I am getting a warning like: "Unable to parse endpoint metadata". This is a message which is a bit suspicious since it is not clear to understand easily;  

`call = callAgent.startCall([{ communicationUserId: userToCall }], placeCallOptions );`

Can you define what should I set to this variable?

**Comment by ddematheu2** [comment]
The variable should be an Azure Communication Services User Id. 

When you provision a token: https://codepen.io/team/Azure-CommunicationServices/pen/BaQJdja

There is an identity attached to it.
