### ISSUE TITLE
No file sharing documentation for stateful chat components of the UI library ?

### ISSUE THREAD

**Issue by jorgecolon413** [Azure-Samples/communication-services-javascript-quickstarts#139]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report 
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> https://azure.github.io/communication-ui-library/?path=/story/quickstarts-statefulclient--page 

### Any log messages given by the failure
> I can see previously shared files on a thread from when we tested the ChatComposite capabilities for file sharing. But can't seem to find any implementation of this functionality for the stateful clients. 

### Expected/desired behavior
>Is there a similar sample for file sharing using the stateful chat components ?

### OS and Version?
> Windows 10. 
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by palatter** [comment]
@jorgecolon413 

Would this quickstart sample be suitable for your needs?

https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-filesharing-chat-composite

**Comment by palatter** [comment]
We are closing this issue since we haven’t heard back from you for 10 days. Please feel free to reopen this issue if you have any questions.
