### ISSUE TITLE
Forbidden error when initiating chat from ACS to Teams

### ISSUE THREAD

**Issue by kundurmutt** [Azure-Samples/communication-services-javascript-quickstarts#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map
> navigate to localhost:8080
>Paste teams link and thread id link
> Have tried unescaped and escaped variants of teams and thread id link
> Connects successfully to teams - shows waiting in lobby - 
> can successfully admit user into teams lobby from teams
> Send a message from index.html page - nothing received in Teams
> Send a messages from Teams to acs user - nothing received in Teams
> Web Browser console shows that user token is successfully created, thread id is also successfully created however
> 403 Forbidden Error : Initiator does not have permission to perform requested operation

### Any log messages given by the failure
>Console
403 Forbidden Error : Initiator does not have permission to perform requested operation
### Expected/desired behavior
> Should be able to post chat message from ACS to Teams and vice versa

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful

> Teams interop form was submitted and activated sucessfully on tenant - also I am global Teams Admin. Teams video/audio calling from other Hero sample(s) works as expected - issue seems to be with chat only.
![acsteamserror](https://user-images.githubusercontent.com/38834499/122388849-cf32fc80-cf5f-11eb-8965-770342b34953.png)

![acsteamserror](https://user-images.githubusercontent.com/38834499/122388626-92ff9c00-cf5f-11eb-8754-06563ef1a0d9.png)

> Thanks! We'll be in touch soon.

**Comment by kundurmutt** [comment]
Dear Team,
Any updates on this issue?
Thanks

**Comment by angiurgiu** [comment]
Hello @kundurmutt, it seems like this meeting is a channel meeting as opposed to a regular one. I can see that from the format of the thread id in the attached screenshots. Unfortunately ACS users can't chat within channels, that is blocked by Teams for any users that are not members of the respective channel. At this time there is no way for external/ACS users to be part of a Teams channel. This behavior is the same with federated Teams users.

Please start/create a regular meeting, you can do that from within your calendar view as opposed to your channel view.

**Comment by angiurgiu** [comment]
Issue has been confirmed as resolved

**Comment by kundurmutt** [comment]
Thank you for your response. The sample works now as per your guidance.

**Comment by davrous** [comment]
Hi @angiurgiu, shouldn't we then close this issue? :)
