### ISSUE TITLE
If this ui is flexibility with vue js 

### ISSUE THREAD

**Issue by dinesh2907** [Azure-Samples/communication-services-javascript-quickstarts#161]
I am not able to run the 
@azure/communication-react module in my vue js project they throwing an error as 
Uncaught (in promise) TypeError: dispatcher is null
Can u please help me out

**Comment by vhuseinova-msft** [comment]
We are closing this issue since we haven’t heard back from you for more than 10 days. Feel free to reopen this issue if you have any questions.
