### ISSUE TITLE
${task} should be ${task.taskId}] for variable "uniqueFileName" in communication-services-javascript-quickstarts/ui-library-filesharing-chat-composite/app/src/AtachmentUploadOptions.tsx line 33

### ISSUE THREAD

**Issue by naoyat-ms** [Azure-Samples/communication-services-javascript-quickstarts#287]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Follow the Prerequisites instructions on the below README.
https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-filesharing-chat-composite

Create a blob storage named "uploads" on Azure Storage Account.

Edit line 40 in app/src/AtachmentUploadOptions.tsx as below. (in order to run at local using app and api)
url: `http://localhost:7071/api/uploadFileToAzureBlobStore?filename=${uniqueFileName}`,

Run the application based on the README.

The file sharing feature fails when doing so.

### Fix done for successful run
>

${task} should be ${task.taskId}] for variable "uniqueFileName" in line 33 for communication-services-javascript-quickstarts/ui-library-filesharing-chat-composite/app/src/AtachmentUploadOptions.tsx

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Leah-Xia-Microsoft** [comment]
Hi @naoyat-ms, thank you for reporting this issue.
The fix has been merged through this PR: https://github.com/Azure-Samples/communication-services-javascript-quickstarts/pull/288.
Therefore, we are closing this issue. Please check it out and let us know if you have any questions.
