### ISSUE TITLE
1 on 1 video sample does not include instruction to add token to Line #55

### ISSUE THREAD

**Issue by pierceboggan** [Azure-Samples/communication-services-javascript-quickstarts#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Clone the `add-1-on-1-video-calling` repo.
2. Follow the instructions on the sample README to install packages and run the app.

### Any log messages given by the failure
N/A

### Expected/desired behavior
Sample works by following instructions.

### Actual behavior
User token must be added to Line #55.

### OS and Version?
> GitHub Codespaces

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ddematheu2** [comment]
Thanks, added instructions.
