### ISSUE TITLE
After turning on camera on web with quickstart stateful call, video feed is not streamed to videogallery component, 

### ISSUE THREAD

**Issue by zhenwei2972** [Azure-Samples/communication-services-javascript-quickstarts#42]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by carocao-msft** [comment]
When you are the only person in the call you should see yourself in the video gallery.
If there is someone else in the call it is expected you will not be seen in the video gallery but in the localVideoTile on the bottom right :) Let me know if this solves the issue!

**Comment by smartstoremx** [comment]
the stop button does not work

**Comment by smartstoremx** [comment]
where can I find the last update source code sample please?

**Comment by dmceachernmsft** [comment]
Hello! sounds like you having issues with the end call button? which sample are you having issues with?

**Comment by alkwa-msft** [comment]
Closing this old issue. Feel free to reopen if it still going on and if you can provide any more details. Thanks!
