### ISSUE TITLE
callClient.createTeamsCallAgent is not a function  with  Calling SDK 1.5.4-beta.1

### ISSUE THREAD

**Issue by mwerghemmi** [Azure-Samples/communication-services-javascript-quickstarts#79]
Hi, 

I am trying to implement Teams interop with ACS calling SDK (web) when i use the 1.5.4-beta.1 i am having the error 
"callClient.createTeamsCallAgent is not a function" while i can instantiate createTeamsCallAgent with version 1.7.0-alpha.20220718.1. 

I am trying to test the transfer feature (with Teams identity) 

can you please help which version of the web calling SDK i should use ? 

@xixian73  can you support please ? 

Many thanks !

**Comment by prprabhu-ms** [comment]
This isn't quite the right forum for this request.

The functions in the OP are from [@azure/communication-calling](https://www.npmjs.com/package/@azure/communication-calling). The best place to get answers would be the the [Azure Communication Services topic on Microsoft Q&A](https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/global/external-sign-in.html)

But as stated in the OP, `callClient.createTeamsCallAgent` is a new method, available in the alpha versions of the package, but not yet released to the beta channel. It should become available as the team runs it through their QA processes and promotes it to beta.

Hope that helps!
