### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of null (reading 'scrollTop') (src/components/MessageThread.tsx:705)

### ISSUE THREAD

**Issue by peershaped** [Azure-Samples/communication-services-javascript-quickstarts#89]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I used the statefulChatClient demo from this repo. 
https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-starting-with-chat-stateful
I used the code of the demo and added it to my existing project without any changes.
When i start and load the chat screen it works but sometimes while loading previous messages it just crashes wit a messages: See below
It seems to get the token and then it starts loading the messages and at a certain point it just crashes and shows me the message.

It might be related to this https://github.com/Azure/communication-ui-library/pull/506
Not sure

### Any log messages given by the failure
> 
```
Unhandled Rejection (TypeError): Cannot read properties of null (reading 'scrollTop')
(anonymous function)
src/components/MessageThread.tsx:705
fulfilled
http://localhost:3000/static/js/5.chunk.js:120977:24
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

Also in the console the following error appears:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollTop')
    at MessageThread.tsx:705:1
    at Generator.next (<anonymous>)
    at fulfilled (MessageStatusIndicator.tsx:166:1)
  ```
### Expected/desired behavior
> This should not happen

### OS and Version?
> Windows 10. Google chrome

### Versions
> 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by carocao-msft** [comment]
Hi Thanks for raising this issue, we are looking into this

**Comment by peershaped** [comment]
Thanks for looking in to it! If you have any questions let me know!

**Comment by alkwa-msft** [comment]
@peershaped  Hello. I am checking out this issue. At this time I have recreated a large thread and have tried to trigger the scrollTop issue you have run into. I unfortunately have not had luck in a repro. Is it possible to share a what version of communication-react you are using?

I thing a gify could also be helpful as well if you are able to consistently repro.

My suggestion is that if you are using 1.3.1 of communication-react perhaps we can try to update to 1.4.0 communication-react?

**Comment by peershaped** [comment]
@alkwa-msft Thanks for the suggestion. I upgraded to version 1.4.0

In the mean time i have tried a few things.
I  tried to use the chat adapter and the regular ChatComposite component.
As suggested in the docs:
https://azure.github.io/communication-ui-library/?path=/docs/composites-chat-basicexample--basic-example

I seem to run in to the same issue. 
After a while i see the same message. This is a new thread with only two messages.

I was not clear on our react version in my initial question. Maybe this has something to do with this?
I see that the examples are build on top of React 16.
We are running React 18.2.0

Could this be an issue? 

Below the example component I created
```
import { FC,  useCallback, useEffect, useMemo, useRef } from "react";
import {
  ChatAdapter,
  FluentThemeProvider,
  DEFAULT_COMPONENT_ICONS,
  useAzureCommunicationChatAdapter,
  fromFlatCommunicationIdentifier,
  ChatComposite
} from "@azure/communication-react";
import { AzureCommunicationTokenCredential, CommunicationUserIdentifier } from "@azure/communication-common";
import { initializeIcons, registerIcons } from "@fluentui/react";


type ChatClientProps  = {
  userId: string,
  displayName: string,
  thread: any,
  hideSendbox?: boolean,
  accessToken: string
}
const ChatClient: FC<ChatClientProps> = ({
  userId,
  displayName,
  thread,
  hideSendbox = false,
  accessToken
}): JSX.Element => {
  const initialLoad = useRef(false);
  const endpointUrl = process.env.REACT_APP_COMMUNICATION_SERVICE_DOMAIN;
  const credential = useMemo(() => new AzureCommunicationTokenCredential(accessToken), [accessToken]);
  const userChatId = useMemo(
    () => fromFlatCommunicationIdentifier(userId) as CommunicationUserIdentifier,
    [userId]
  );

  const adapterAfterCreate = useCallback(
    async (adapter: ChatAdapter): Promise<ChatAdapter> => {
      adapter.on("messageReceived", (listener) => {
        console.log("messageReceived")
      });
      adapter.on("error", (e) => {
        console.error(e);
      });
      if (initialLoad) {
        adapter.fetchInitialData();
        initialLoad.current = true
      }
      return adapter;
      
    },
    [userId, thread, initialLoad]
  );

  const adapter = useAzureCommunicationChatAdapter({
    endpoint: endpointUrl,
    userId: userChatId,
    displayName,
    credential,
    threadId: thread.chatThreadId
  }, adapterAfterCreate);

  useEffect(() => {
    if (initialLoad) {
      
      initialLoad.current = true
    }
  })
  useEffect(() => {
    const disposeAdapter = (): void => adapter?.dispose();
    window.addEventListener("beforeunload", disposeAdapter);
    return () => {
      console.log("cleanup adapter");
      window.removeEventListener("beforeunload", disposeAdapter);
    }
  }, [adapter]);
  
  initializeIcons();
  registerIcons({ icons: DEFAULT_COMPONENT_ICONS });

  if (!adapter || !thread || !displayName || !userId) {
    return (<p>initializing..</p>)
  }
  return (
    <FluentThemeProvider>
      <ChatComposite
        adapter={adapter}
        options={{
          errorBar: true,
          topic: true
        }}
      />
    </FluentThemeProvider>
  );
}

export default ChatClient;
```

In the parent component I use it like this:
```
{
  chatAccessToken &&
  currentUser &&
  mainThread  && (
  <div style={{width: "500px", height: "600px"}}>
    <ChatClient
      userId={currentUser.chatId}
      thread={mainThread}
      displayName={currentUser.displayName}
      accessToken={chatAccessToken}
    />
  </div>
)}
```

**Comment by alkwa-msft** [comment]
Thanks for sharing additional information around the scenario and a code snippet. I will be checking this out. Thanks!

**Comment by peershaped** [comment]
I created a small repo with a very distilled version of the code.
https://github.com/peershaped/chat-example
Running this I don't see the page crashing. 
I do see the console errors which make our current project crash when switching back and forth between detail and fullscreen page
```
MessageThread.tsx:715 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollTop')
    at MessageThread.tsx:715:1
    at Generator.next (<anonymous>)
    at fulfilled (MessageStatusIndicator.tsx:174:1)
 ```

**Comment by alkwa-msft** [comment]
Thank you once again for taking the time to file this issue and to create this repo for us to focus on the issue.

I wanted to update on this thread. I have been able to repro the issue. I was able to find the exact line by disabling source maps. I need to run some ideas by another engineer on my team and to look into a fix.

**Comment by alkwa-msft** [comment]
@peershaped  We have the fix in the latest beta build of the ui library

[1.4.1-beta.1](https://www.npmjs.com/package/@azure/communication-react/v/1.4.1-beta.1)

I was unable to repro the issue based on how I reproduced it before. Feel free to try it out and share with us if you have any feedback!

**Comment by peershaped** [comment]
Hi @alkwa-msft Sorry for the late reply. It seems to have solved the issue. Thanks for the quick responses and solutions!
