### ISSUE TITLE
Will this work for a ReactJS  SPA ?

### ISSUE THREAD

**Issue by fpereiramapfrepr** [Azure-Samples/communication-services-javascript-quickstarts#97]
Hi,

I'm trying to get a token for the ACS API dynamically, instead of going to Azure Portal and using the "Identities & User Access Tokens" generate button and pasting them in the apps.

I already have a ReactApp that uses Azure AD and MSAL...

```
ReactDOM.render(
    <React.StrictMode>
        <MsalProvider instance={msalInstance}>
            <App />
        </MsalProvider>
    </React.StrictMode>,
    document.getElementById("root")
);
```

Trying to find out what are the next steps I saw this code that is for node in JS.  Think that something like this can be implemented on the App.js and pass it as a props to all the other controls.

```
async function createIdentityAndIssueToken(resourceEndpoint) {
    const client = new CommunicationIdentityClient(resourceEndpoint, credential);
    return await client.createUserAndToken(["chat"]);
}
```

Is there any example or clear documentation on how to create a Token based on an Azure AD identity?

Thanks for the great work!

**Comment by petrsvihlik** [comment]
Azure Communication Services requires developers to generate user and access token credentials inside of a trusted authentication service. 

Here's how you can build a trusted service using:
- [Azure Functions](https://learn.microsoft.com/en-us/azure/communication-services/tutorials/trusted-service-tutorial)
- [Node.js](https://learn.microsoft.com/en-us/azure/communication-services/samples/trusted-auth-sample?pivots=programming-language-javascript)
  - [Related GitHub repository](https://github.com/Azure-Samples/communication-services-authentication-hero-nodejs)
- [.NET](https://learn.microsoft.com/en-us/azure/communication-services/samples/trusted-auth-sample?pivots=programming-language-csharp)
  - [Related GitHub repository](https://github.com/Azure-Samples/communication-services-authentication-hero-csharp)

Please never try to run code that requires access to secrets  (`CLIENT_SECRET` or connection string) from the client-side JavaScript. Any implementations of the `TokenCredential` that access secrets (e.g. `EnvironmentCredential`, `ClientSecretCredential`, etc.) are considered unsafe to be used from the client side. `InteractiveBrowserCredential` is not yet supported by ACS.

```javascript
async function createIdentityAndIssueToken(resourceEndpoint) {
    // Don't use this from client-side JS
    const client = new CommunicationIdentityClient(resourceEndpoint, credential);
    return await client.createUserAndToken(["chat"]);
}
```

> Is there any example or clear documentation on how to create a Token based on an Azure AD identity?

Azure Communication Services is identity-agnostic, to learn more check out our [conceptual documentation](https://learn.microsoft.com/en-us/azure/communication-services/concepts/identity-model). Specifically, pay attention to the section about [Identity mapping](https://learn.microsoft.com/en-us/azure/communication-services/concepts/identity-model#identity-mapping).

If your Azure AD identities have MS Teams licenses assigned, you can use ACS<->Teams interoperability. Please follow this [tutorial](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/identity/access-token-teams-external-users?tabs=windows&pivots=programming-language-javascript).

**Comment by alkwa-msft** [comment]
Closing this issue as @petrsvihlik  as provided a response above. @fpereiramapfrepr  feel free to re-open if you have any additional comments or questions pertaining to this github issue.

**Comment by fpereiramapfrepr** [comment]
Thanks for the information! Already working on an Azure Function to build a trusted service.
